# Generated by Django 4.0.2 on 2022-02-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invited',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=30)),
                ('job', models.CharField(max_length=30)),
            ],
        ),
    ]
